backend {
  default = "Local"
  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        run-in-background = true
        runtime-attributes = """
          String? docker
          Int? cpu
          String? memory
          Int? disk_size
          Int? preemptible
          Int? maxRetries
          Int? bootDiskSizeGb
        """
        submit = "/usr/bin/env bash ${script}"
      }
    }
  }
}
