#!/usr/bin/env python3
"""
Sensitivity analysis — alternative allele read-count threshold (R1.5).

Re-classifies existing Part2 outputs (_part2_all.tsv) at different alt-read
thresholds K ∈ {2,3,4,5}. Baseline K=2 matches the main pipeline.

The filter is applied at two points (both vary with K):
  1. Pileup proband alt count  ≥ K   (proband_alt_count column)
  2. VCF AD_alt                ≥ K

All other filters (parent alt=0, hard-filter, centromere, repeat, gnomAD,
chrY, depth) are kept as-is — only the proband alt threshold moves.

Output:
  outputs/sensitivity/alt_threshold.json  — per (trio, caller, K): counts
  outputs/sensitivity/alt_threshold.md    — markdown tables + burden test

Usage:
  python scripts/sensitivity_alt_threshold.py
  python scripts/sensitivity_alt_threshold.py --trios brca1,brca2
"""

import argparse
import json

import polars as pl

from _common import (
    OUTPUTS_DIR, TRIOS,
    MIN_VCF_DP, SENSITIVITY_THRESHOLDS,
    burden_test, load_part2_all, sig_star, vaf_breakdown,
)


THRESHOLDS = SENSITIVITY_THRESHOLDS


def count_at_threshold(df: pl.DataFrame, k: int) -> dict:
    """Apply alt≥k to both pileup and AD_alt, keep other filters, count.

    Classification uses the same final set as the main analysis: binom_class
    + manual IGV validation (for FA trios) or binom_class alone (for GIAB).
    Returns dict with mosaic_{snv,indel,all}, het_{snv,indel,all} and the
    mosaic/het ratio.
    """
    pass_all_k = (
        pl.col("pileupDepthFilterTrio")
        & pl.col("pileupParentFilter")
        & (pl.col("proband_alt_count") >= k)
        & (pl.col("AD_alt") >= k)
        & (pl.col("DP") > MIN_VCF_DP)
        & pl.col("HardFilter")
        & pl.col("centromereFilter")
        & pl.col("repeatFullFilter")
        & pl.col("gnomAD_filter")
        & pl.col("sexChrFilter")
    )
    if "igvFilter" in df.columns:
        pass_all_k = pass_all_k & pl.col("igvFilter")
    kept = df.filter(pass_all_k)

    def _c(cls, t):
        return len(kept.filter((pl.col("binom_class") == cls) & (pl.col("Type") == t)))

    mosaic_snv = _c("mosaic", "SNV")
    mosaic_indel = _c("mosaic", "INDEL")
    het_snv = _c("het", "SNV")
    het_indel = _c("het", "INDEL")
    mosaic_all = mosaic_snv + mosaic_indel
    het_all = het_snv + het_indel
    return {
        "mosaic_snv": mosaic_snv, "mosaic_indel": mosaic_indel, "mosaic_all": mosaic_all,
        "het_snv": het_snv, "het_indel": het_indel, "het_all": het_all,
        "mosaic_het_ratio": round(mosaic_all / het_all, 3) if het_all > 0 else None,
    }


def build_markdown(results: dict, thresholds: list[int], trios: list[str]) -> str:
    """Render sensitivity tables in markdown."""
    lines = []
    lines.append("# Sensitivity Analysis — Alternative Allele Read-Count Threshold\n")
    lines.append("*Auto-generated by `scripts/sensitivity_alt_threshold.py`. "
                 "Addresses Reviewer 1 request (R1.5): how do de novo counts "
                 "depend on the minimum proband alt-read threshold?*\n")
    lines.append("The baseline analysis uses **alt≥2** for both the pileup proband "
                 "alt count and the VCF `AD_alt`. Here we vary that threshold to "
                 f"K ∈ {{{', '.join(str(t) for t in thresholds)}}}. All other filters "
                 "(parent alt=0, hard-filter, centromere, repeat, gnomAD AF=0, chrY, "
                 "manual IGV validation) are kept exactly as in the main pipeline. "
                 "Classification uses `binom_class` (depth-aware per-variant "
                 "binomial test; see report §2d / R1.m14).\n")

    for caller_label, caller_key in [("HC (HaplotypeCaller)", "hc"),
                                     ("Mutect2", "mutect2")]:
        lines.append(f"## {caller_label}\n")

        header = "| Trio | " + " | ".join(f"alt≥{k}" for k in thresholds) + " |"
        sep = "|---|" + "|".join(["---:"] * len(thresholds)) + "|"

        lines.append("### Mosaic SNV counts per threshold\n")
        lines.append(header)
        lines.append(sep)
        for t in trios:
            row = results.get(caller_key, {}).get(t, {})
            cells = [str(row.get(str(k), {}).get("mosaic_snv", "")) for k in thresholds]
            label = f"**{t}**" if t == "brca2" else t
            lines.append(f"| {label} | " + " | ".join(cells) + " |")
        lines.append("")

        lines.append("### Het de novo SNV counts per threshold\n")
        lines.append(header)
        lines.append(sep)
        for t in trios:
            row = results.get(caller_key, {}).get(t, {})
            cells = [str(row.get(str(k), {}).get("het_snv", "")) for k in thresholds]
            lines.append(f"| {t} | " + " | ".join(cells) + " |")
        lines.append("")

        lines.append("### Mosaic/het ratio per threshold (SNV+INDEL)\n")
        lines.append("*Lower ratio = het-enriched (likely germline); higher = mosaic-enriched.*\n")
        lines.append(header)
        lines.append(sep)
        for t in trios:
            row = results.get(caller_key, {}).get(t, {})
            cells = []
            for k in thresholds:
                r = row.get(str(k), {}).get("mosaic_het_ratio")
                cells.append(f"{r:.3f}" if r is not None else "—")
            label = f"**{t}**" if t == "brca2" else t
            lines.append(f"| {label} | " + " | ".join(cells) + " |")
        lines.append("")

        lines.append("### Mosaic burden test vs control per threshold\n")
        lines.append("*Conditional binomial exact, one-sided (case > control), mosaic SNV only.*\n")
        lines.append(header)
        lines.append(sep)
        for t in [x for x in trios if x != "control"]:
            row = results.get(caller_key, {}).get(t, {})
            cells = []
            for k in thresholds:
                b = row.get(str(k), {}).get("burden_vs_control", {})
                p = b.get("p_value")
                ratio = b.get("ratio")
                if p is None:
                    cells.append("—")
                else:
                    ratio_s = f"{ratio}x " if ratio is not None else ""
                    cells.append(f"{ratio_s}p={p:.1e} {sig_star(p)}")
            label = f"**{t}**" if t == "brca2" else t
            lines.append(f"| {label} | " + " | ".join(cells) + " |")
        lines.append("")

        lines.append("### Detailed breakdown (mosaic SNV / INDEL / het SNV / INDEL)\n")
        lines.append("| Trio | alt≥ | Mosaic SNV | Mosaic INDEL | Het SNV | Het INDEL |")
        lines.append("|---|---:|---:|---:|---:|---:|")
        for t in trios:
            row = results.get(caller_key, {}).get(t, {})
            for k in thresholds:
                r = row.get(str(k), {})
                lines.append(
                    f"| {t} | {k} | {r.get('mosaic_snv','')} | "
                    f"{r.get('mosaic_indel','')} | {r.get('het_snv','')} | "
                    f"{r.get('het_indel','')} |"
                )
        lines.append("")

    lines.append("## Interpretation\n")
    lines.append("- Signal **robust to threshold** if the brca2/control mosaic-SNV "
                 "ratio (and its p-value) stays significant as K increases. "
                 "Het counts should decline slowly — true heterozygous variants "
                 "typically have many alt reads.")
    lines.append("- Mosaic counts are more sensitive to K by design "
                 "(low-VAF mosaic has few alt reads even at 150x proband coverage).")
    lines.append("- For a proband covered at ~150x and mosaic VAF ≈ 10-37%, "
                 "expected alt reads ≈ 15-55 — so thresholds up to alt≥5 should "
                 "retain most genuine mosaic calls.")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Sensitivity: alt-read threshold")
    parser.add_argument("--trios", default=None,
                        help="Comma-separated trios (default: all 5)")
    parser.add_argument("--thresholds", default=None,
                        help="Comma-separated thresholds (default: 2,3,4,5)")
    parser.add_argument("--output-dir", default=None,
                        help="Output dir (default: outputs/sensitivity/)")
    args = parser.parse_args()

    trios = args.trios.split(",") if args.trios else TRIOS
    thresholds = [int(x) for x in args.thresholds.split(",")] if args.thresholds else THRESHOLDS
    from pathlib import Path
    out_dir = Path(args.output_dir) if args.output_dir else OUTPUTS_DIR / "sensitivity"
    out_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("  Sensitivity — alt-read threshold (R1.5)")
    print("=" * 60)
    print(f"  Trios:      {', '.join(trios)}")
    print(f"  Thresholds: {thresholds}")
    print()

    results: dict = {"hc": {}, "mutect2": {}}

    for caller in ["hc", "mutect2"]:
        print(f"--- {caller} ---")
        for trio in trios:
            df = load_part2_all(trio, caller)
            if df is None:
                print(f"  SKIP {trio}: _part2_all.tsv not found")
                continue
            results[caller][trio] = {}
            per_k = {k: count_at_threshold(df, k) for k in thresholds}
            for k, r in per_k.items():
                results[caller][trio][str(k)] = r
            ms = " ".join(
                f"K={k}:{per_k[k]['mosaic_snv']}/{per_k[k]['het_snv']}"
                for k in thresholds
            )
            print(f"  {trio}: mosaic_SNV/het_SNV → {ms}")

        if "control" not in results[caller]:
            continue
        for trio in [t for t in trios if t != "control"]:
            if trio not in results[caller]:
                continue
            for k in thresholds:
                case_n = results[caller][trio][str(k)]["mosaic_snv"]
                ctrl_n = results[caller]["control"][str(k)]["mosaic_snv"]
                results[caller][trio][str(k)]["burden_vs_control"] = burden_test(case_n, ctrl_n)
        print()

    json_path = out_dir / "alt_threshold.json"
    with open(json_path, "w") as f:
        json.dump({"thresholds": thresholds, "trios": trios, "results": results},
                  f, indent=2)
    print(f"JSON → {json_path}")

    md_path = out_dir / "alt_threshold.md"
    md_path.write_text(build_markdown(results, thresholds, trios))
    print(f"Markdown → {md_path}")


if __name__ == "__main__":
    main()
